# Generated by Django 2.2.4 on 2019-08-22 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190822_2101'),
        ('users', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='movies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie'),
        ),
    ]
