# Generated by Django 2.2.4 on 2019-08-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='isPublish',
            field=models.BooleanField(default=True),
        ),
    ]
