# Generated by Django 2.2.4 on 2019-08-25 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='bornYear',
            field=models.IntegerField(default=1996, validators=[django.core.validators.MaxValueValidator(1800), django.core.validators.MinValueValidator(2019)]),
            preserve_default=False,
        ),
    ]
