# Generated by Django 2.2.4 on 2019-08-25 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_director_bornyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='bornYear',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2019), django.core.validators.MinValueValidator(1800)]),
        ),
    ]
