# Generated by Django 2.2.4 on 2019-08-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190812_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
