# Generated by Django 2.2.4 on 2019-08-25 18:32

import base.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190825_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='director_name',
            field=models.CharField(default='default_director', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=base.helper.get_file_path),
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
