# Generated by Django 2.2.4 on 2019-08-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190817_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(default='default-name', max_length=64),
            preserve_default=False,
        ),
    ]
