# Generated by Django 2.2.4 on 2019-08-24 21:37

import base.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190822_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=base.helper.get_file_path),
        ),
    ]
